branches:
  only:
    - master
    - develop

notifications:
  slack:
    rooms:
      - tp18:VdIe1#flask-api-travis
    on_success: change
    on_failure: always

language: python
sudo: required
dist: xenial
python: "3.8"
services:
  - postgresql

addons:
  ssh_known_hosts:
    - 127.0.0.1
  postgresql: '11'
  apt:
    packages:
      - postgresql-11
      - postgresql-client-11
env:
  global:
  - PGPORT=5433

install:
  - export PYENV_VERSION=3.8.13
  - pip install -r requirements.txt
  - pip install --upgrade pytest
  - export FLASK_APP='api/api.py'
  - export FLASK_ENV='development'
  - export MONANT_ENABLE_ES=False
before_script:
  - psql -c 'CREATE DATABASE monant_api_test;'
  - psql -c "CREATE USER monant_api WITH ENCRYPTED PASSWORD 'exposed';"
  - psql -c 'GRANT ALL ON DATABASE monant_api_test TO monant_api;'
  - export MONANT_POSTGRES_TEST_HOST=localhost
  - export MONANT_POSTGRES_TEST_PORT=5433
  - export MONANT_POSTGRES_TEST_PASSWORD=exposed
script:
  - pytest tests
deploy:
  # deploy dev to the staging environment
  - provider: script
    script: bash scripts/deploy.sh staging
    on:
      branch: develop
  # deploy master to the production environment
  - provider: script
    script: bash scripts/deploy.sh production
    on:
      branch: master
